### PR TITLE
Julia 0.3 -> 0.6 upgrade; use AbstractVectors with `missing` values for inputs; new plotting

### PR DESCRIPTION
**Pull request by ablaom**
Warning: This is my very first pull-request, so please go easy on me :-)

Changes:

1. Upgrade julia syntax to 0.6

2. The `DataArray` dendency has been dumped in favour of the built-in `AbstractVector` type with `missing` values, as provided by `Missings` package (to be part of standard library in 0.7). 

3. The plotting method depending on `Winston` has been exchanged for a `Plots` recipe, which requires only a light-weight dependency, `RecipesBase`. (So you only load full-blown plotting if you acutally need it.)

4. Some updates to the README, including a longer example (from docs/example.jl) and removal of a broken link.

If these changes are adopted, I am happy to do Julia 0.7/1.0 upgrade in due course.

Thanks in advance for your review.

### CODE REVIEW

**Comment by diegozea** [comment]
Hello Anthony,

Thanks you very much for this! I haven't touched this package in a while. Maybe you will be interested also in https://github.com/davidavdav/ROCAnalysis.jl which is far more complete, registrered and could benefit from the same kind of love ;)

This PR looks pretty great :) I've found only one problem: 
`rocplot.jl` was deleted, but it's still included with `include("rocplot.jl")` and the plot recipe is missing. I guess you have the plot recipe file locally, but it didn't get into the PR.

I've written a plot recipe for `ROCAnalysis` a lot time ago, but it is not longer working: https://github.com/JuliaML/MLPlots.jl

Cheers,

**Comment by ablaom** [comment]
Thanks for the feedback and for pointing out the `ROCanalysis.jl` package which I missed. I have added the forgotten file. 

The file `appveyor.yml` and `.travisym` files still need updating. Perhaps you could do this or explain how I should do this?

Cheers

**Comment by diegozea** [comment]
Thanks! You're welcome!

You can use https://github.com/JuliaCI/Appveyor.jl to easily update `appveyor.yml`. Travis is a little more complicated, but something like this should work:
```
language: julia
os:
  - linux
  - osx
sudo: required
julia:
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone("https://github.com/diegozea/ROC.jl.git"); Pkg.build("ROC"); Pkg.test("ROC"; coverage=true)'
```

**Comment by ablaom** [comment]
After pointing travis file temporalily to the fork containing the proposal I see that 
the proposed branch now successfully tests on x86 versions 0.6 and 0.7 (with depreciation warnings).

Will now point travis file back to original diegozea repo. Should then be good to go.

**Comment by diegozea** [comment]
Thanks @ablaom !! I will merge it :) There are some tests that are failing, but I will take q look into that later.

**Pull request merged**
